//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заболевания
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заболевания()
        {
            this.ТипЗаболевания = "вирус";
            this.ИнкубационныйПериод = 5;
            this.Пациенты = new HashSet<Пациенты>();
        }
    
        public string Название { get; set; }
        public string ТипЗаболевания { get; set; }
        public string Возбудитель { get; set; }
        public string МКБ_10 { get; set; }
        public Nullable<decimal> Смертность { get; set; }
        public string Воздействие { get; set; }
        public string Симптомы { get; set; }
        public string СпособПередачи { get; set; }
        public int ИнкубационныйПериод { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациенты> Пациенты { get; set; }
    }
}
