//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИзоляцияНаКарантин
    {
        public int НомерИзолятора { get; set; }
        public System.DateTime НачалоКарантина { get; set; }
        public System.DateTime КонецКарантина { get; set; }
        public string Заболевание { get; set; }
        public int ИД_Пациента { get; set; }
    
        public virtual Пациенты Пациенты { get; set; }
    }
}
