//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лечение
    {
        public int ИД_Лечения { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаОкончания { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public int ИД_Врача { get; set; }
        public int ИД_Пациента { get; set; }
        public int ИД_Препарата { get; set; }
        public int ИД_Оборудования { get; set; }
    
        public virtual ЛекарственныеПрепараты ЛекарственныеПрепараты { get; set; }
        public virtual МедицинскийПерсонал МедицинскийПерсонал { get; set; }
        public virtual Оборудование Оборудование { get; set; }
        public virtual Пациенты Пациенты { get; set; }
    }
}
