//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЛекарственныеПрепараты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЛекарственныеПрепараты()
        {
            this.КурсПриема = 7;
            this.Лечение = new HashSet<Лечение>();
        }
    
        public int ИД_Препарата { get; set; }
        public string НазваниеПрепарата { get; set; }
        public string ПриЗаболевании { get; set; }
        public int КурсПриема { get; set; }
        public string Применение { get; set; }
        public int Количество { get; set; }
        public decimal Стоимость { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лечение> Лечение { get; set; }
    }
}
