//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class МедицинскийПерсонал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public МедицинскийПерсонал()
        {
            this.Лечение = new HashSet<Лечение>();
            this.Палаты = new HashSet<Палаты>();
        }
    
        public int ИД { get; set; }
        public System.DateTime ДатаПринятияНаРаботу { get; set; }
        public string Должность { get; set; }
        public string Квалификация { get; set; }
        public decimal Зарплата { get; set; }
        public int НомерКабинета { get; set; }
    
        public virtual Гражданин Гражданин { get; set; }
        public virtual Кабинеты Кабинеты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лечение> Лечение { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Палаты> Палаты { get; set; }
    }
}
