//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Палаты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Палаты()
        {
            this.КоличествоМест = 3;
            this.Этаж = 5;
            this.Оборудование = new HashSet<Оборудование>();
            this.Пациенты = new HashSet<Пациенты>();
        }
    
        public int НомерПалаты { get; set; }
        public int КоличествоПациентов { get; set; }
        public int КоличествоМест { get; set; }
        public int Этаж { get; set; }
        public int ИД_Персонала { get; set; }
    
        public virtual МедицинскийПерсонал МедицинскийПерсонал { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Оборудование> Оборудование { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Пациенты> Пациенты { get; set; }
    }
}
