//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OsipovCourseWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пациенты()
        {
            this.РезультатЛечения = "проходит лечение";
            this.ИзоляцияНаКарантин = new HashSet<ИзоляцияНаКарантин>();
            this.Лечение = new HashSet<Лечение>();
        }
    
        public int ИД { get; set; }
        public string НомерМедКарты { get; set; }
        public System.DateTime ДатаПоступления { get; set; }
        public Nullable<System.DateTime> ДатаВыписки { get; set; }
        public int НомерПалаты { get; set; }
        public string Диагноз { get; set; }
        public Nullable<decimal> ПлатаЗаЛечение { get; set; }
        public string РезультатЛечения { get; set; }
    
        public virtual Гражданин Гражданин { get; set; }
        public virtual Заболевания Заболевания { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ИзоляцияНаКарантин> ИзоляцияНаКарантин { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лечение> Лечение { get; set; }
        public virtual Палаты Палаты { get; set; }
    }
}
